routes/web.php
<?php

use App\Http\Controllers\CarouselController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ColorController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WelcomeController;
use App\Models\Cart;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [WelcomeController::class, 'welcome']);
Route::get('/categories/{category}/product', [WelcomeController::class, 'productList'])->name('frontend.products.index');
Route::get('/products/{product}', [WelcomeController::class, 'productDetails'])->name('frontend.products.show');
Route::get('/api/cart', function () {
    return response()->json([
        'data' => [
            'product' => [
                'id' => 1,
                'title' => 'This is product 1'
            ]
        ]
    ]);
});

Route::get('/cart', function () {
    return view('cart');
});

Route::get('/cart-items', function () {

    $cartItems = auth()->user()->cartItems;

    $cartItems->load('product');

    $data = [];
    foreach ($cartItems as $value) {
        $data[] =  [
            'id' => $value->id,
            'title' => $value->product->title,
            'qty' => $value->qty,
            'unitPrice' => $value->product->price,
            'totalPrice' => $value->qty * $value->product->price
        ];
    }

    return response()->json([
        'status' => true,
        'data' => $data
    ]);
});

Route::delete('/cart-items/{cartItem}', function (Cart $cartItem) {
    $cartItem->delete();
    return response()->json([
        'status' => true,
        'message' => 'Successfully Deleted'
    ]);
});


require __DIR__ . '/auth.php';

Route::middleware('auth')->prefix('dashboard')->group(function () {

    Route::get('/api/my-profile', function () {
        return response()->json([
            'myProfile' => auth()->user()
        ]);
    });

    Route::post('/products/{product}/comments', [CommentController::class, 'store'])->name('products.comments.store');

    Route::get('/', function () {
        return view('home');
    })->name('home');

    Route::get('carousels-trash', [CarouselController::class, 'trash'])->name('carousels.trash');
    Route::patch('carousels-trash/{id}', [CarouselController::class, 'restore'])->name('carousels.restore');
    Route::delete('carousels-trash/{id}', [CarouselController::class, 'delete'])->name('carousels.delete');
    Route::resource('carousels', CarouselController::class);
    Route::get('category-trash', [CategoryController::class, 'trash'])->name('categories.trash');
    Route::patch('category-trash/{id}', [CategoryController::class, 'restore'])->name('categories.restore');
    Route::delete('category-trash/{id}', [CategoryController::class, 'delete'])->name('categories.delete');
    Route::get('categories/pdf', [CategoryController::class, 'downloadPdf'])->name('categories.pdf');

    Route::resource('categories', CategoryController::class);

    Route::get('colors-trash', [ColorController::class, 'trash'])->name('colors.trash');
    Route::patch('colors-trash/{id}', [ColorController::class, 'restore'])->name('colors.restore');
    Route::delete('colors-trash/{id}', [ColorController::class, 'delete'])->name('colors.delete');
    Route::get('colors/pdf', [ColorController::class, 'downloadPdf'])->name('colors.pdf');

    Route::resource('colors', ColorController::class);

    Route::get('products-trash', [ProductController::class, 'trash'])->name('products.trash');
    Route::patch('products-trash/{id}', [ProductController::class, 'restore'])->name('products.restore');
    Route::delete('products-trash/{id}', [ProductController::class, 'delete'])->name('products.delete');
    Route::get('products/pdf', [ProductController::class, 'downloadPdf'])->name('products.pdf');
    Route::resource('products', ProductController::class);

    Route::get('/profile', function () {
        return view('users.profile');
    });

    Route::prefix('users')->name('users.')->group(function () {
        Route::get('/', [UserController::class, 'index'])->name('index');
        Route::get('/{user}', [UserController::class, 'show'])->name('show');
        Route::get('/{user}/change-role', [UserController::class, 'changeRole'])->name('change_role');
        Route::patch('/{user}/change-role', [UserController::class, 'updateRole'])->name('update_role');
    });

    Route::post('/products/{product}/cart', [CartController::class, 'store'])->name('products.cart.store');
});

Route::fallback(function () {
    dd('Tomar chaoa puron korte parbona.....');
});

app/Models/Color.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Color extends Model
{
    use HasFactory,SoftDeletes;

    protected $guarded = [];

    // public function products()
    // {
    //     return $this->belongsToMany(Product::class);
    // }

}

app/Http/Controllers/ColorController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ColorRequest;
use App\Models\Color;
use Barryvdh\DomPDF\Facade\Pdf;

class ColorController extends Controller
{
    public function index()
    {
        $colors = Color::all();
        return view('colors.index', compact('colors'));
    }

    public function create()
    {
        return view('colors.create');
    }

    public function store(ColorRequest $request)
    {
        $data = [
            'title' => $request->title,
            'color_code' => $request->color_code,
        ];

        Color::create($data);

        return redirect()
            ->route('colors.index')
            ->withMessage('Created Successfully!');
    }

    public function edit(Color $color)
    {
        return view('colors.edit', compact('color'));
    }

    public function update(ColorRequest $request, Color $color)
    {
        $data = [
            'title' => $request->title,
            'color_code' => $request->color_code,
        ];

        $color->update($data);

        return redirect()
            ->route('colors.index')
            ->withMessage('Updated Successfully!');
    }

    public function show(Color $color)
    {
        return view('colors.show', compact('color'));
    }

    public function destroy(Color $color)
    {
        $color->delete();
        return redirect()
            ->route('colors.index')
            ->withMessage('Deleted Successfully!');
    }

    public function trash()
    {
        $colors = Color::onlyTrashed()->get();
        return view('colors.trash', compact('colors'));
    }

    public function restore($id)
    {
        $color = Color::onlyTrashed()->find($id);
        $color->restore();

        return redirect()
            ->route('colors.trash')
            ->withMessage('Restored Successfully!');
    } 

    public function delete($id)
    {
        $color = Color::onlyTrashed()->find($id);
        $color->forceDelete();

        return redirect()
            ->route('colors.trash')
            ->withMessage('Deleted Successfully!');
    } 

    public function downloadPdf()
    {
        $colors = Color::all();
        $pdf = Pdf::loadView('colors.pdf', compact('colors'));
        return $pdf->download('Color-list.pdf');
    }

}

resources/views/colors/create.blade.php
<x-master>
    <x-slot:title>
        Color Details
    </x-slot>

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Color Create</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <button type="button" class="btn btn-sm btn-outline-secondary">Export PDF</button>
            </div>
            <a href="{{ route('colors.index') }}">
                <button type="button" class="btn btn-sm btn-outline-primary">
                    <span data-feather="list"></span>
                    List
                </button>
            </a>
        </div>
    </div>

    <x-forms.errors />

    <form action="{{ route('colors.store') }}" method="post">
        @csrf

        <x-forms.input type="text" name="title" label="Title" :value="old('title')" required placeholder="Enter Title" />

        <x-forms.input type="color" name="color_code" label="Color Code" :value="old('color_code')" required />

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

</x-master>

resources/views/colors/edit.blade.php
<x-master>
    <x-slot:title>
        Colors Details
    </x-slot:title>

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Category Edit</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <button type="button" class="btn btn-sm btn-outline-secondary">Export PDF</button>
            </div>
            <a href="{{ route('categories.index') }}">
                <button type="button" class="btn btn-sm btn-outline-primary">
                    <span data-feather="list"></span>
                    List
                </button>
            </a>
        </div>
    </div>

    <x-forms.errors />

    <form action="{{ route('colors.update', $color->id) }}" method="post">
        @csrf
        @method('patch')

        <x-forms.input type="text" name="title" label="Title" :value="old('title',$color->title)" required placeholder="Enter Title" />

        <x-forms.input type="color" name="color_code" label="Color Code" :value="old('color_code')" required />

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>



</x-master>

resources/views/colors/index.blade.php
<x-master>
    <x-slot:title>
        Color List
        </x-slot>

        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Colors</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                <div class="btn-group me-2">
                    <a href="{{ route('colors.pdf') }}">
                        <button type="button" class="btn btn-sm btn-outline-primary">PDF</button>
                    </a>
                    <button type="button" class="btn btn-sm btn-outline-secondary">Export Excel</button>
                    <a href="{{ route('colors.trash') }}">
                        <button type="button" class="btn btn-sm btn-outline-danger">Trash</button>
                    </a>
                </div>
                <a href="{{ route('colors.create') }}">
                    <button type="button" class="btn btn-sm btn-outline-primary">
                        <span data-feather="plus"></span>
                        Add New
                    </button>
                </a>
            </div>
        </div>

        <x-forms.message />

        <table class="table">
            <thead>
                <tr>
                    <th>SL#</th>
                    <th>Title</th>
                    <th>Color Code</th>
                    <th width="180">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach($colors as $color)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $color->title }}</td>
                    <td>
                        <div style="background-color: {{$color->color_code}};">{{ $color->color_code }}</div>
                    </td>

                    <td class="d-flex">
                        <a class="btn btn-sm btn-outline-info" href="{{ route('colors.show', $color->id) }}">Show</a>
                        <a class="btn btn-sm btn-outline-info" href="{{ route('colors.edit', $color->id) }}">Edit</a>
                        <form action="{{ route('colors.destroy', $color->id) }}" method="post">
                            @csrf
                            @method('delete')
                            <button class="btn btn-sm btn-outline-danger">Delete</button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>

</x-master>

resources/views/colors/pdf.blade.php
<table border="1">
    <thead>
        <tr>
            <th>SL#</th>
            <th>Title</th>
        </tr>
    </thead>
    <tbody>
        @foreach($categories as $category)
        <tr>
            <td>{{ $loop->iteration }}</td>
            <td>{{ $category->name }}</td>
        </tr>
        @endforeach
    </tbody>
</table>

resources/views/colors/show.blade.php
<x-master>
    <x-slot:title>
        Category Details
    </x-slot:title>

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Colors Details</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <button type="button" class="btn btn-sm btn-outline-secondary">Export PDF</button>
            </div>
            <a href="{{ route('colors.index') }}">
                <button type="button" class="btn btn-sm btn-outline-primary">
                    <span data-feather="list"></span>
                    List
                </button>
            </a>
        </div>
    </div>

    <h1>Title: {{ $color->title }}</h1>
    {{-- <p>Is Active?: {{ $color->is_active ? 'Yes' : 'No' }} </p> --}}
    <div style="background-color: {{$color->color_code}}; height:300px; display:flex;align-items:center; justify-content:center; font-size:27px;">
        THe color is like this
    </div>
</x-master>

resources/views/colors/trash.blade.php
<x-master>
    <x-slot:title>
        Trashed Color List
        </x-slot>

        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Colors</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                <div class="btn-group me-2">
                    <a href="{{ route('colors.pdf') }}">
                        <button type="button" class="btn btn-sm btn-outline-primary">PDF</button>
                    </a>
                    <button type="button" class="btn btn-sm btn-outline-secondary">Export Excel</button>
                    <a href="{{ route('colors.index') }}">
                        <button type="button" class="btn btn-sm btn-outline-danger">List</button>
                    </a>
                </div>
                <a href="{{ route('colors.create') }}">
                    <button type="button" class="btn btn-sm btn-outline-primary">
                        <span data-feather="plus"></span>
                        Add New
                    </button>
                </a>
            </div>
        </div>

        <x-forms.message />

        <table class="table">
            <thead>
                <tr>
                    <th>SL#</th>
                    <th>Title</th>
                    <th>Color Code</th>
                    <th width="180">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach($colors as $color)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $color->title }}</td>
                    <td>
                        <div style="background-color: {{$color->color_code}};">{{ $color->color_code }}</div>
                    </td>

                    <td class="d-flex">
                        <form action="{{ route('colors.restore', $color->id) }}" method="post">
                            @csrf
                            @method('patch')
                            <button class="btn btn-sm btn-outline-warning" onclick="return confirm('Are you sure want to restore?')">Restore</button>
                        </form>
                        <form action="{{ route('colors.delete', $color->id) }}" method="post">
                            @csrf
                            @method('delete')
                            <button class="btn btn-sm btn-outline-danger" onclick="return confirm('Are you sure want to delete?')">Delete</button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>

</x-master>